http:
  host: "0.0.0.0"
  port: "7081"
  reconnectionCount: "1000"
  reconnectionTime: "3"
  
httpRequest:
  host: "system-flight-api.us-e2.cloudhub.io"
  port: "80"
  timeout: "10000"
  basePath: "/sysapi"
  reconnectionCount: "5000"
  reconnectionTime: "3"
  
json:
  logger:
    application:
      version: "1.0.3"
      name: "process-flight-api"